# Generated by Django 2.1.4 on 2018-12-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(choices=[(1, 'Criança'), (2, 'Adulto')], max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('whats', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInvitation', models.IntegerField()),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('descr', models.CharField(max_length=50)),
                ('eventFk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventManager.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('confirmData', models.DateTimeField(auto_now_add=True)),
                ('contactFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventManager.Contact')),
                ('eventFk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventManager.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ReportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30, null=True)),
                ('logo', models.CharField(max_length=30, null=True)),
                ('tp', models.CharField(max_length=30)),
                ('contactFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventManager.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='reportMode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventManager.ReportMode'),
        ),
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(to='eventManager.Service'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eventManager.SiteModel'),
        ),
        migrations.AddField(
            model_name='event',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventManager.Type'),
        ),
        migrations.AddField(
            model_name='companions',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventManager.Guests'),
        ),
    ]
