# Generated by Django 2.1.4 on 2019-01-03 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0003_auto_20181227_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companions',
            name='tp',
            field=models.CharField(choices=[(1, 'Criança'), (2, 'Adulto')], max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
