# Generated by Django 2.1.4 on 2019-01-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0004_auto_20190103_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='companions',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventManager.CompanionsType'),
        ),
    ]
