# Generated by Django 2.1.4 on 2019-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0005_auto_20190104_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionstype',
            name='tp',
            field=models.CharField(max_length=20),
        ),
    ]
