# Generated by Django 2.1.4 on 2019-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0006_auto_20190104_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companions',
            name='tp',
            field=models.CharField(choices=[(1, 'Criança'), (2, 'Adulto')], max_length=1),
        ),
        migrations.DeleteModel(
            name='CompanionsType',
        ),
    ]
