# Generated by Django 2.1.4 on 2019-01-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0010_auto_20190110_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tp',
            new_name='descr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reportMode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='site',
        ),
        migrations.DeleteModel(
            name='ReportMode',
        ),
        migrations.DeleteModel(
            name='SiteModel',
        ),
    ]
