# Generated by Django 2.1.4 on 2019-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0011_auto_20190110_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.FileField(upload_to='imgs'),
        ),
    ]
