# Generated by Django 2.1.4 on 2019-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0012_auto_20190111_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
