# Generated by Django 2.1.4 on 2019-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0014_auto_20190112_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.AddField(
            model_name='service',
            name='site',
            field=models.CharField(default='test.com', max_length=50),
            preserve_default=False,
        ),
    ]
