# Generated by Django 2.1.4 on 2019-01-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0017_auto_20190116_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='url',
            new_name='image',
        ),
    ]
