# Generated by Django 2.1.4 on 2019-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0019_auto_20190116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
