# Generated by Django 2.1.4 on 2019-01-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0021_auto_20190116_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='eventFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='eventManager.Event'),
            preserve_default=False,
        ),
    ]
