# Generated by Django 2.1.4 on 2019-02-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0023_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('num', models.DecimalField(decimal_places=8, max_digits=19)),
                ('eventFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='eventManager.Event')),
            ],
        ),
    ]
